### PR TITLE
Fix C inlining issues

### LINKED ISSUE #201: Not working with bitcode_enabled NO flag
i am currently playing with Cocoapods-keys & observed that it doesn't work if bitcode_enabled is NO. values are embeded as plain text in Keys.Framework/Keys file. Can you please confirm if this is the expected behaviour?

### PR DESCRIPTION
**Pull request by ashfurrow**
I've tested this with Artsy's codebase to make sure it still works 👍 It puts the data in an NSString, and uses `characterAtIndex:` Objective-C function calls, which are unlikely to be inlined by the compile. This might incur some performance penalty, but, that's probably fine.

I also made some refactors to use less Objective-C runtime stuff and make this easier to maintain. The downside of this approach is that it loads _all_ keys upfront in `init`, which has potential further performance impacts. This now optimizes for creating fewer instances of the `Keys` object, since creating each one is more expensive but each key access is free. 

The refactor is in a separate commit in case you'd like to keep the original implementation. I have verified both commits solve the problem of inlining keys in the binaries.

Fixes #201.

### CODE REVIEW

**Comment by orta** [comment]
CI fail is a dumb style linting thing - other than that, this looks and sounds good to m. Get it green and I'll ship a release 👍

File: lib/key_master.rb [hunk 1]
```diff
@@ -84,7 +84,7 @@ def render_erb(erb_template)
     end
 
     def key_data_arrays
-      Hash[@indexed_keys.map { |key, value| [key, value.map { |i| name + "Data[#{i}]" }.join(', ')] }]
+      Hash[@indexed_keys.map { |key, value| [key, value.map { |i| "[" + name + "Data characterAtIndex:#{i}]" }.join(', ')] }]
```
Comment (ashfurrow) [inline lib/key_master.rb]:
```suggestion
      Hash[@indexed_keys.map { |key, value| [key, value.map { |i| '[' + name + "Data characterAtIndex:#{i}]" }.join(', ')] }]
```

**Comment by ashfurrow** [comment]
🍏

**Comment by muddsar** [comment]
Thanks @ashfurrow & @orta for quickly resolving this issue. It looks amazing

**Comment by orta** [comment]
Rockin'
