### PR TITLE
Fixes undefined method '*' for nil:NilClass issue on first run

### LINKED ISSUE #113: NoMethodError - undefined method `*' for nil:NilClass Error during install
I added `cocoapods-keys` to a project today, and had a slight issue with initial install. 

```
$ gem install cocoapods-keys
$ vim Podfile
$ pod install
CocoaPods-Keys has detected a keys mismatch for your setup.
 What is the key for TraktAPIKey
 > ABCDEF123456789 

Saved TraktAPIKey to TraktTopTen.
```

All well and good, but then immediately after I got the following issue:

------ 

### Command

```
/Users/pi/.gem/bin/pod install
```

### Report

* What did you do?
Ran `pod install` after adding `cocoapods-keys` to my `Podfile`.

* What did you expect to happen?
`cocoapods-keys` to request the key, and exit cleanly.

* What happened instead?
The following stack trace

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 7.0.1 (7A1001)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fd384d791ce6472307a25da5a4499eef0b096eb8
```

### Plugins

```
cocoapods-keys    : 1.5.2
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
use_frameworks!
link_with 'TraktTopTen', 'TraktTopTenTests'
pod 'SwiftyJSON', '~> 2.3'
pod 'Haneke', '~> 1.0.1'

# Use cocoapods-keys to store the Trakt API key
plugin 'cocoapods-keys', {
  :project => "TraktTopTen",
  :keys => [
    "TraktAPIKey"
  ]}
```

### Error

```
NoMethodError - undefined method `*' for nil:NilClass
/Users/pi/.gem/gems/cocoapods-keys-1.5.2/lib/key_master.rb:32:in `generate_data'
/Users/pi/.gem/gems/cocoapods-keys-1.5.2/lib/key_master.rb:20:in `initialize'
/Users/pi/.gem/gems/cocoapods-keys-1.5.2/lib/plugin.rb:34:in `new'
/Users/pi/.gem/gems/cocoapods-keys-1.5.2/lib/plugin.rb:34:in `setup'
/Users/pi/.gem/gems/cocoapods-keys-1.5.2/lib/plugin.rb:98:in `install!'
/Users/pi/.gem/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/pi/.gem/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/pi/.gem/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/pi/.gem/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/pi/.gem/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/pi/.gem/bin/pod:23:in `load'
/Users/pi/.gem/bin/pod:23:in `<main>'
```

------ 

After this, I ran `pod install` again, and it exited cleanly:

```
$ pod install
Updating local specs repositories

CocoaPods 0.39.0.rc.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Fetching podspec for `Keys` from `Pods/CocoaPodsKeys`
Downloading dependencies
Using Haneke (1.0.1)
Installing Keys (1.0.0)
Using SwiftyJSON (2.3.0)
Generating Pods project
Integrating client project
Sending stats
Sending stats
```

### PR DESCRIPTION
**Pull request by rpassis**
Fixes #113 by ensuring the `keys_length` doesn't return nil.

### CODE REVIEW

File: lib/key_master.rb [hunk 1]
```diff
@@ -28,8 +28,8 @@ def generate_data
       verify_keychain_integrity
 
       # Generate a base64 hash string that is ~25 times the length of all keys
-
-      @data_length = @keys.values.map(&:length).reduce(:+) * (20 + rand(10))
```
Comment (segiddins) [inline lib/key_master.rb]: this could just be changed to `reduce(0, :+)`

Comment (rpassis) [inline lib/key_master.rb]: Cool thanks, that's much better! I'll update and send a new PR.

**Comment by orta** [comment]
Oh nice, I had forgot this was a bug! Thanks @rpassis 

4-up on 6-2-16 at 8 35 pm compiled

**Comment by orta** [comment]
screen shot 2016-06-02 at 8 45 14 pm
